### ISSUE TITLE
in mode='local' unable to fetch equity_history

### ISSUE THREAD

**Issue by UltimateDip** [aeron7/nsepythonserver#2]
`equity_history()` is not working in the local setup. Please take a look at the following solution.  

When I was using the code in my local machine, I manually changed the mode to local  and removed the `.json()` from [this line](https://github.com/aeron7/nsepythonserver/blob/79c3c7534fbcfd4c335838683ac9b578d241beec/nsepythonserver/rahu.py#L45)

**Comment by aeron7** [comment]
Just update to the lastest version. https://forum.unofficed.com/t/nse-results-giving-jsondecodeerror/1315/7 

And use nsepython for local
